Site/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Site.Models;
using CommTool;
using System.Data;
using Newtonsoft.Json;
using System.Web.Helpers;

namespace Site.Controllers
{
    public class FormsController : Controller
    {
        //
        // GET: /Forms/

        public ActionResult Index()
        {
            List<cForms> aobForms = cForms.Find();
            List<FormList> objFormList = new List<FormList>();
            if (aobForms.Count > 0)
            {
                foreach (var item in aobForms)
                {
                    objFormList.Add(new FormList { iID = item.iID, FormName = item.sFormName,Edit=false,Views=false });
                }
               
            }
            return View(objFormList.ToList());
        }
        [HttpPost]
        public ActionResult Index(FormCollection frmColl)
        {
            var edit = frmColl.GetValues("Edit");
            if (edit.Length > 0)
            {
                foreach (var id in edit)
                {
                    int ids = Convert.ToInt32(id.ToString());
                    List<cUserAccessForm> aobjForms = cUserAccessForm.Find(" objForms = " + ids);
                    if (aobjForms.Count > 0)
                    {
                        cForms objForm = cForms.Get_ID(ids);
                    }
                    else
                    {
                        cUserAccessForm objAccess = cUserAccessForm.Create();
                        
                    }
                    
                   


                }
            }
            var view = frmColl.GetValues("View");
            if (view.Length > 0)
            {
                foreach (var id in view)
                {
                    string ids = id.ToString();
                }
            }


            List<cForms> aobForms = cForms.Find();
            List<FormList> objFormList = new List<FormList>();
            if (aobForms.Count > 0)
            {
                foreach (var item in aobForms)
                {
                    objFormList.Add(new FormList { iID = item.iID, FormName = item.sFormName });
                }

            }
            return View(objFormList.ToList());
        }
    }
}

Site/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
    var grid=new WebGrid(source:Model,rowsPerPage:2);
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>My First Grid</title>

    @*Style Sheet For Grid:-*@
    <link rel="stylesheet" type="text/css" media="screen" href="css/jquery-ui-1.9.2.custom.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />

    <link type="text/css" href="http://jqueryrock.googlecode.com/svn/trunk/css/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
    <link type="text/css" href="http://jqueryrock.googlecode.com/svn/trunk/jqgrid/css/ui.jqgrid.css" rel="stylesheet" />

    @*JS For Grid:-*@
    <script type="text/javascript" src="js/jquery-1.8.3.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.9.2.custom.js"></script>
    <script src="js/grid.locale-en.js" type="text/javascript"></script>
    <script src="js/jquery.jqGrid.min.js" type="text/javascript"></script>

    <script type="text/javascript" src="http://jqueryrock.googlecode.com/svn/trunk/js/jquery-1.8.3.js"></script>
    <script type="text/javascript" src="http://jqueryrock.googlecode.com/svn/trunk/js/jquery-ui-1.9.2.custom.js"></script>
    <script src="http://jqueryrock.googlecode.com/svn/trunk/jqgrid/js/grid.locale-en.js" type="text/javascript"></script>
    <script src="http://jqueryrock.googlecode.com/svn/trunk/jqgrid/js/jquery.jqGrid.min.js" type="text/javascript"></script>

    <style type="text/css">
        table.gridtable {
            font-family: verdana,arial,sans-serif;
            font-size: 11px;
            color: #333333;
            border-width: 1px;
            border-color: #666666;
            border-collapse: collapse;
        }

            table.gridtable th {
                border-width: 1px;
                padding: 8px;
                border-style: solid;
                border-color: #666666;
                background-color: #dedede;
            }

            table.gridtable td {
                border-width: 1px;
                padding: 8px;
                border-style: solid;
                border-color: #666666;
                background-color: #ffffff;
            }
    </style>
    <script type="text/javascript">

    </script>
</head>
<body>
    <div style="margin-top:400px;height:auto; width:auto; margin-left:200px;border:2px solid red">
        @using (Html.BeginForm("Index", "Forms",FormMethod.Post))
        {
                @grid.GetHtml(
                tableStyle:"gridtable",
                columns:
                    grid.Columns(
                        @*Here I Will Add Checkbox Column*@
                        grid.Column(format:@<text><input type="checkbox" name="Edit" value="@item.iID" /></text>, header:"Edit"),
                        grid.Column(format:@<text><input type="checkbox" name="View" value="@item.iID" /></text>, header:"View"),
                        grid.Column("iID","Form ID"),
                        grid.Column("FormName", "Form Name")
                    )
                )
            <input type="submit" value="Update" />
        }
    </div>
   
</body>
</html>